export const COMMON_ENGLISH_WORDS = [
  "able",
  "after",
  "again",
  "air",
  "also",
  "back",
  "base",
  "best",
  "bird",
  "blue",
  "book",
  "bring",
  "call",
  "care",
  "city",
  "clear",
  "cold",
  "come",
  "dark",
  "day",
  "deep",
  "door",
  "down",
  "early",
  "easy",
  "even",
  "ever",
  "fast",
  "field",
  "fire",
  "first",
  "food",
  "free",
  "fresh",
  "good",
  "green",
  "hand",
  "home",
  "kind",
  "land",
  "late",
  "light",
  "long",
  "made",
  "main",
  "make",
  "moon",
  "near",
  "next",
  "open",
  "page",
  "place",
  "plain",
  "quiet",
  "rain",
  "read",
  "river",
  "road",
  "room",
  "safe",
  "same",
  "short",
  "slow",
  "small",
  "soft",
  "sound",
  "stone",
  "sure",
  "table",
  "take",
  "time",
  "tree",
  "true",
  "warm",
  "water",
  "white",
  "wind",
  "word",
  "work",
  "world",
];

export const ENGLISH_SENTENCE_SNIPPETS = [
  "the quiet road was clear",
  "bring the blue book home",
  "fresh water is near the table",
  "the small room felt warm",
  "a clear day brings good light",
  "the green field was open",
  "read the next short page",
  "the stone path was safe",
  "soft rain fell after dark",
  "make time for quiet work",
  "the river road turns left",
  "a kind word can help",
  "the first door was open",
  "warm air moved through the room",
  "the white moon rose early",
];

export const PORTUGUESE_SENTENCE_SNIPPETS = [
  "a casa fica perto do rio",
  "o dia claro ajuda o trabalho",
  "leva o livro azul para casa",
  "a rua calma estava livre",
  "a agua fresca esta na mesa",
  "o vento frio chegou cedo",
  "uma palavra simples ajuda",
  "o campo verde estava aberto",
];
